# Generated by Django 2.0.6 on 2019-06-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicFeature',
            fields=[
                ('usgs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('kind', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.IntegerField()),
            ],
        ),
    ]
