# Generated by Django 2.0.6 on 2019-06-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GeographicFeature',
            fields=[
                ('usgs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('kind', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.GeographicFeature')),
                ('nws_daily_endpoint', models.URLField(blank=True)),
                ('nws_hourly_endpoint', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='geographicfeature',
            name='state',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
