# Generated by Django 2.0.6 on 2019-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='nws_daily_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='nws_hourly_endpoint',
            field=models.URLField(blank=True),
        ),
    ]
