# Generated by Django 2.0.6 on 2019-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20190609_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicfeature',
            name='state',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
