# Generated by Django 2.0.6 on 2019-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('period_index', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('forecast_long', models.TextField()),
                ('forecast_short', models.TextField()),
                ('is_daytime', models.BooleanField()),
                ('temperature', models.IntegerField()),
                ('precipitation_probability', models.TextField()),
                ('icon_type', models.TextField(default='CLOUD')),
            ],
        ),
    ]
