# Generated by Django 2.0.6 on 2019-07-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('period_index', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_daytime', models.BooleanField()),
                ('temperature', models.IntegerField()),
                ('forecast_short', models.TextField()),
                ('forecast_long', models.TextField()),
                ('precipitation_probability', models.TextField()),
                ('icon_type', models.TextField()),
            ],
            options={
                'get_latest_by': ['start'],
            },
        ),
    ]
