# Generated by Django 2.0.6 on 2019-07-10 04:06

from django.db import migrations, models
import moistmaster.utils


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringsession',
            name='created_time',
            field=models.DateTimeField(default=moistmaster.utils.utc_now),
        ),
        migrations.AlterField(
            model_name='wateringsession',
            name='session_end',
            field=models.DateTimeField(null=True),
        ),
    ]
